version: "3"

services:


  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data/

  app1:
    build: ./django_app
    container_name: django-gunicorn1
    restart: always
    # env_file:
    #   - django.env
    volumes:
        - app1_data:/app1_storage
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 django_app.wsgi:application"

    depends_on:
        - db

  app2:
    build: ./django_app
    container_name: django-gunicorn2
    restart: always
    # env_file:
    #   - django.env
    # volumes:
    #     - app1_data:/app1_storage
    ports:
      - "8001:8001"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8001 django_app.wsgi:application"

    depends_on:
        - db

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2

volumes:
    app1_data:
    pgdata: